cms:
    resource: "@CmsBundle/Resources/config/routing.yml"
    prefix:   /

amarina:
    resource: "@AmarinaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

