cms:
    resource: "@CmsBundle/Resources/config/routing.yml"
    prefix:   /

amarina:
    resource: "@AmarinaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Sonata Admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#Admin Tree on theh dashboard
cmf_tree:
    resource: .
    type: 'cmf_tree'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"