<?php

namespace AmarinaBundle\Repository;

/**
 * CurrentFinishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrentFinishRepository extends \Doctrine\ORM\EntityRepository
{
}
