<?php

namespace AmarinaBundle\Repository;

/**
 * FinishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinishRepository extends \Doctrine\ORM\EntityRepository
{
}
