<?php

namespace AmarinaBundle\Repository;

/**
 * MuebleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuebleRepository extends \Doctrine\ORM\EntityRepository
{
}
