<?php

namespace AmarinaBundle\Repository;

/**
 * UseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UseRepository extends \Doctrine\ORM\EntityRepository
{
}
