services:
#    cms.example:
#        class: CmsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    # cms.basic_cms.phpcr.initializer:
    #     class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
    #     arguments:
    #         - My custom initializer
    #         - ["/cms/pages", "/cms/posts", "/cms/routes"]
    #     tags:
    #         - { name: doctrine_phpcr.initializer }

    cms_basiccms.phpcr.initializer.site:
        class: CmsBundle\Initializer\SiteInitializer
        tags:
            - { name: doctrine_phpcr.initializer, priority: 50 }

# Sonata Admin
    cms.basic_cms.admin.page:
        class: CmsBundle\Admin\PageAdmin
        arguments:
            - ''
            - CmsBundle\Document\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: Page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    cms.basic_cms.admin.post:
        class: CmsBundle\Admin\PostAdmin
        arguments:
            - ''
            - CmsBundle\Document\Post
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: 'Blog Posts' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    cms.basic_cms.menu_provider:
        class: Symfony\Cmf\Bundle\MenuBundle\Provider\PhpcrMenuProvider
        arguments:
            - '@cmf_menu.factory'
            - '@doctrine_phpcr'
            - /cms/pages
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: knp_menu.provider }